### ISSUE TITLE
MWException from line 519

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#246]
**Setup**
- MediaWiki 	1.25.6 (01b4001)21:49, 20 May 2016
- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- Semantic MediaWiki	2.4.1 (af78257) 12:28, 12 July 2016
- Semantic Maps	3.4.0 (563e653) 22:12, 18 September 2016
- Maps	3.8.1 (978b928) 13:37, 7 September 2016

**Query**
```
{{#ask:
 [[Category:Locations]]
 |?Has coordinates
 |format=googlemaps
 |template=Google Maps Link
}}
```

**Issue**
[1f6ffe7d] /wiki/Semantic_Maps_examples/Using_templates_%28queries%29 MWException from line 519 of /.../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php: There is no result format for 'map'.

**Backtrace**
```
#0 /.../w/extensions/SemanticMediaWiki/includes/params/SMW_ParamFormat.php(148): SMWQueryProcessor::getResultPrinter(string)
#1 /.../w/vendor/param-processor/param-processor/src/ParamDefinition.php(496): SMWParamFormat->formatValue(string, ParamProcessor\Param, array, array)
#2 /.../w/vendor/param-processor/param-processor/src/Param.php(225): ParamProcessor\ParamDefinition->format(ParamProcessor\Param, array, array)
#3 /.../w/vendor/param-processor/param-processor/src/Processor.php(378): ParamProcessor\Param->process(array, array, ParamProcessor\Options)
#4 /.../w/vendor/param-processor/param-processor/src/Processor.php(352): ParamProcessor\Processor->processOneParam()
#5 /.../w/vendor/param-processor/param-processor/src/Processor.php(290): ParamProcessor\Processor->doParamProcessing()
#6 /.../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(51): ParamProcessor\Processor->processParameters()
#7 /.../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(377): SMWQueryProcessor::getProcessedParams(array, array)
#8 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(172): SMWQueryProcessor::getQueryAndParamsFromFunctionParams(array, integer, integer, boolean, SMW\DIWikiPage)
#9 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(115): SMW\AskParserFunction->doFetchResultsForRawParameters(array)
#10 /.../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): SMW\AskParserFunction->parse(array)
#11 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string)
#12 /.../w/includes/parser/Parser.php(3783): call_user_func_array(Closure, array)
#13 /.../w/includes/parser/Parser.php(3517): Parser->callParserFunction(PPFrame_DOM, string, array)
#14 /.../w/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPFrame_DOM)
#15 /.../w/includes/parser/Parser.php(3334): PPFrame_DOM->expand(PPNode_DOM, integer)
#16 /.../w/includes/parser/Parser.php(1232): Parser->replaceVariables(string)
#17 /.../w/includes/parser/Parser.php(435): Parser->internalParse(string)
#18 [internal function]: Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#19 /.../w/includes/StubObject.php(105): call_user_func_array(array, array)
#20 /.../w/includes/StubObject.php(129): StubObject->_call(string, array)
#21 /.../w/includes/content/WikitextContent.php(333): StubObject->__call(string, array)
#22 /.../w/includes/content/WikitextContent.php(333): StubObject->parse(string, Title, ParserOptions, boolean, boolean, integer)
#23 /.../w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#24 /.../w/includes/poolcounter/PoolWorkArticleView.php(140): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#25 /.../w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#26 /.../w/includes/page/Article.php(674): PoolCounterWork->execute()
#27 /.../w/includes/actions/ViewAction.php(44): Article->view()
#28 /.../w/includes/MediaWiki.php(463): ViewAction->show()
#29 /.../w/includes/MediaWiki.php(269): MediaWiki->performAction(Article, Title)
#30 /.../w/includes/MediaWiki.php(634): MediaWiki->performRequest()
#31 /.../w/includes/MediaWiki.php(482): MediaWiki->main()
#32 /.../w/index.php(41): MediaWiki->run()
#33 {main}
```

**Comment by JeroenDeDauw** [comment]
That looks like https://github.com/SemanticMediaWiki/SemanticMaps/issues/118

Try upgrading to 3.4.1

**Comment by kghbln** [comment]
> Try upgrading to 3.4.1

Yeah, everything fluffy now with 3.4.1
