### ISSUE TITLE
Missing JavaScript files?

### ISSUE THREAD

**Issue by Nikerabbit** [JeroenDeDauw/Maps#292]
### Setup

- MW version: master
- DB (MySQL etc.):
- PHP version: hhvm 3.12.7
- Maps version: 4.0.2
- SMW version (if applicable): 2.4.3

### Issue

```
2016-12-05 19:39:15 translatewiki.net translatewiki_net-bw_: [896cda00b0ffae93bb863ef4] /w/load.php?debug=false&lang=pt&modules=ext.sm.common%7Cext.sm.fi.openlayersajax&skin=vector&version=0vvwrbr   MWException from line 804 of /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/srv/mediawiki/tags/2016-12-05_13:49:33/extensions/Maps/src/SemanticMaps/src/ext.sm.common.js"
#0 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderFileModule.php(356): ResourceLoaderFileModule->readScriptFiles(array)
#1 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderModule.php(627): ResourceLoaderFileModule->getScript(ResourceLoaderContext)
#2 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderModule.php(595): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#3 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoader.php(1009): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#4 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoader.php(735): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#5 /srv/mediawiki/tags/2016-12-05_13:49:33/load.php(54): ResourceLoader->respond(ResourceLoaderContext)
#6 {main}
2016-12-05 19:39:15 translatewiki.net translatewiki_net-bw_: [896cda00b0ffae93bb863ef4] /w/load.php?debug=false&lang=pt&modules=ext.sm.common%7Cext.sm.fi.openlayersajax&skin=vector&version=0vvwrbr   MWException from line 804 of /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/srv/mediawiki/tags/2016-12-05_13:49:33/extensions/Maps/src/SemanticMaps/src/services/OpenLayers/ext.sm.openlayersajax.js"
#0 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderFileModule.php(356): ResourceLoaderFileModule->readScriptFiles(array)
#1 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderModule.php(627): ResourceLoaderFileModule->getScript(ResourceLoaderContext)
#2 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoaderModule.php(595): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#3 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoader.php(1009): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#4 /srv/mediawiki/tags/2016-12-05_13:49:33/includes/resourceloader/ResourceLoader.php(735): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#5 /srv/mediawiki/tags/2016-12-05_13:49:33/load.php(54): ResourceLoader->respond(ResourceLoaderContext)
#6 {main}
```

Is there on `src` too much?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting. This is caused by https://github.com/JeroenDeDauw/Maps/commit/8f2894fabe1ebfc932af7aecba9686cf998f6b3c such brittle code...

**Comment by JeroenDeDauw** [comment]
Please close if fixed

@Nikerabbit do you know if MW has some test thing to make sure all these paths are correct? I'd like to avoid silly issues like this in the future, and apparently just looking at a map in my browser is not enough

**Comment by Nikerabbit** [comment]
As far as I know core does have resource loader structure test that checks that all referenced files are present.

**Comment by JeroenDeDauw** [comment]
Going to assume this is fixed, reopen if not
