### ISSUE TITLE
Catch Nominatim errors

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#322]
### Setup

- MW version: 1.28.1
- DB (MySQL etc.): 5.6.36
- PHP version: 5.6.30-0+deb8u1
- Maps version: 4.1.0
- SMW version (if applicable): 2.4.6

### Issue

Nominatim has server issues (503 service unavailable) today so it sometimes trigger this error when I try to save a page:
```
[b8fdd9f1c171f2fd5ead161b] /?title=Adresse:99_Place_de_la_Cath%C3%A9drale_(Munich)&action=submit FileFetcher\FileFetchingException from line 30 of /home/vhosts/fabien/archi-mediawiki/vendor/jeroen/file-fetcher/src/SimpleFileFetcher.php: Could not fetch file: https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=99+Place+de+la+Cath%C3%A9drale+Munich+France

Backtrace:

#0 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/src/Geocoders/NominatimGeocoder.php(31): FileFetcher\SimpleFileFetcher->fetchFile(string)
#1 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/geocoders/Maps_OldGeocoderAdapter.php(29): Maps\Geocoders\NominatimGeocoder->geocode(string)
#2 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/Geocoders.php(213): MapsOldGeocoderAdapter->geocode(string)
#3 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/Geocoders.php(194): Maps\Geocoders::getGeocodedAsArray(MapsOldGeocoderAdapter, string)
#4 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/Geocoders.php(182): Maps\Geocoders::getGeocoded(MapsOldGeocoderAdapter, string)
#5 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/Geocoders.php(137): Maps\Geocoders::geocode(string, string)
#6 /home/vhosts/fabien/archi-mediawiki/extensions/Maps/includes/parserhooks/Maps_Geocode.php(111): Maps\Geocoders::attemptToGeocode(string, string, boolean)
#7 /home/vhosts/fabien/archi-mediawiki/extensions/Validator/src/legacy/ParserHook.php(377): MapsGeocode->render(array)
#8 /home/vhosts/fabien/archi-mediawiki/extensions/Validator/src/legacy/ParserHook.php(294): ParserHook->validateAndRender(array, integer)
#9 [internal function]: ParserHook->renderFunction(Parser, string, string)
#10 /home/vhosts/fabien/archi-mediawiki/extensions/Validator/src/legacy/ParserHook.php(336): call_user_func_array(array, array)
#11 /home/vhosts/fabien/archi-mediawiki/extensions/Validator/src/legacy/ParserHook.php(610): ParserHook->renderFunctionObj(Parser, PPTemplateFrame_DOM, array)
#12 [internal function]: ParserHookCaller->runFunctionHookObj(Parser, PPTemplateFrame_DOM, array)
#13 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3374): call_user_func_array(array, array)
#14 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3098): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#15 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#16 /home/vhosts/fabien/archi-mediawiki/extensions/ParserFunctions/ParserFunctions_body.php(106): PPFrame_DOM->expand(PPNode_DOM)
#17 [internal function]: ExtParserFunctions::ifObj(Parser, PPTemplateFrame_DOM, array)
#18 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3374): call_user_func_array(string, array)
#19 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3098): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#20 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#21 /home/vhosts/fabien/archi-mediawiki/extensions/ParserFunctions/ParserFunctions_body.php(104): PPFrame_DOM->expand(PPNode_DOM)
#22 [internal function]: ExtParserFunctions::ifObj(Parser, PPTemplateFrame_DOM, array)
#23 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3374): call_user_func_array(string, array)
#24 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3098): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#25 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#26 /home/vhosts/fabien/archi-mediawiki/extensions/ParserFunctions/ParserFunctions_body.php(123): PPFrame_DOM->expand(PPNode_DOM)
#27 [internal function]: ExtParserFunctions::ifeqObj(Parser, PPTemplateFrame_DOM, array)
#28 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3374): call_user_func_array(string, array)
#29 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3098): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#30 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#31 /home/vhosts/fabien/archi-mediawiki/extensions/Loops/Loops.php(187): PPFrame_DOM->expand(PPNode_DOM)
#32 [internal function]: ExtLoops::pfObj_loop(Parser, PPTemplateFrame_DOM, array)
#33 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3374): call_user_func_array(array, array)
#34 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3098): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#35 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#36 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(3251): PPFrame_DOM->expand(PPNode_DOM)
#37 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#38 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(2912): PPFrame_DOM->expand(PPNode_DOM, integer)
#39 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(1265): Parser->replaceVariables(string)
#40 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/parser/Parser.php(441): Parser->internalParse(string)
#41 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/content/WikitextContent.php(330): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#42 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#43 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/EditPage.php(3946): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#44 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/EditPage.php(3879): EditPage->doPreviewParse(WikitextContent)
#45 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/EditPage.php(2594): EditPage->getPreviewText()
#46 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/EditPage.php(634): EditPage->showEditForm()
#47 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/actions/EditAction.php(59): EditPage->edit()
#48 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/actions/SubmitAction.php(38): EditAction->show()
#49 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/MediaWiki.php(495): SubmitAction->show()
#50 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/MediaWiki.php(289): MediaWiki->performAction(Article, Title)
#51 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/MediaWiki.php(851): MediaWiki->performRequest()
#52 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/includes/MediaWiki.php(512): MediaWiki->main()
#53 /home/vhosts/fabien/archi-mediawiki/vendor/mediawiki/core/index.php(43): MediaWiki->run()
#54 {main}
```

Would it be possible to catch these errors so my whole wiki isn't paralyzed when Nominatim is down?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue. Failure in the geocoder should indeed not bring your wiki down.
