### ISSUE TITLE
InvalidArgumentException from line 238 of "ObjectFactory.php": Provided specification is not an array.

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#616]
**Setup**
- MediaWiki 	1.34.1 (64676b5)
- PHP 	7.2.24-0ubuntu0.18.04.4 (apache2handler)
- MariaDB 	10.1.44-MariaDB-0ubuntu0.18.04.1
- Maps | 7.18.0 (9f41431) 00:44, 16 April 2020

**Issue**

Originally reported here: https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/77

When trying to access special page "SpecialPages" I get the following error:

```
[e089edda4e1ca9638d2dd9a8] /wiki/Sp%C3%A9cial:Pages_sp%C3%A9ciales InvalidArgumentException from line 238 of /../w/vendor/wikimedia/object-factory/src/ObjectFactory.php: Provided specification is not an array.

```
**Backtrace**
```
#0 /../w/vendor/wikimedia/object-factory/src/ObjectFactory.php(131): Wikimedia\ObjectFactory::validateSpec(string, array)
#1 /../w/vendor/wikimedia/object-factory/src/ObjectFactory.php(102): Wikimedia\ObjectFactory::getObjectFromSpec(string, array)
#2 /../w/includes/specialpage/SpecialPageFactory.php(447): Wikimedia\ObjectFactory->createObject(string, array)
#3 /../w/includes/specialpage/SpecialPageFactory.php(478): MediaWiki\Special\SpecialPageFactory->getPage(string)
#4 /../w/includes/specials/SpecialSpecialpages.php(56): MediaWiki\Special\SpecialPageFactory->getUsablePages(User)
#5 /../w/includes/specials/SpecialSpecialpages.php(44): SpecialSpecialpages->getPageGroups()
#6 /../w/includes/specialpage/SpecialPage.php(575): SpecialSpecialpages->execute(NULL)
#7 /../w/includes/specialpage/SpecialPageFactory.php(611): SpecialPage->run(NULL)
#8 /../w/includes/MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#9 /../w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#10 /../w/includes/MediaWiki.php(527): MediaWiki->main()
#11 /../w/index.php(44): MediaWiki->run()
#12 {main}

```

As soon as I remove Maps the issue goes away.

**Comment by JeroenDeDauw** [comment]
Needs update https://github.com/JeroenDeDauw/Maps/blob/master/src/MapsSetup.php#L56
